#!/bin/bash

set -eux

root_dir="${PWD}"

# Inputs
CONCOURSE_PIPELINE_RESOURCE_DIR="${root_dir}/${CONCOURSE_PIPELINE_RESOURCE_DIR:?"\$CONCOURSE_PIPELINE_RESOURCE_DIR not set"}"
FLY_BINARY_DIR="${root_dir}/${FLY_BINARY_DIR:?"\$FLY_BINARY_DIR not set"}"

export GOPATH="${PWD}/gopath"
export PATH="${GOPATH}/bin:${PATH}"

export FLY_LOCATION="${FLY_BINARY_DIR}/s3-out"

go get github.com/onsi/ginkgo/ginkgo

"${CONCOURSE_PIPELINE_RESOURCE_DIR}/bin/test" acceptance
