#!/bin/bash

set -eu

root_dir="$PWD"

# Inputs
: "${WL_DIR:?}"
: "${GOPATH:?}"

export GOPATH="${root_dir}/${GOPATH}"

export PATH="${PATH}:${GOPATH}/bin"

echo "installing vendored version of ginkgo"
go install "${WL_DIR}/vendor/github.com/onsi/ginkgo/ginkgo"

"${GOPATH}/${WL_DIR}/scripts/unit-tests"
