#!/bin/bash

set -eu

# Inputs
: "${WL_PATH:?}"
: "${GOPATH:?}"

root_dir="$PWD"

export GOPATH="${root_dir}/${GOPATH}"
export PATH="${PATH}:${GOPATH}/bin"

echo "installing vendored version of ginkgo"
go install "${WL_PATH}/vendor/github.com/onsi/ginkgo/ginkgo"

"${GOPATH}/src/${WL_PATH}/scripts/integration-tests"
