#!/bin/bash

set -eux

root_dir="${PWD}"

# Inputs
CONCOURSE_PIPELINE_RESOURCE_DIR="${root_dir}/${CONCOURSE_PIPELINE_RESOURCE_DIR:?"\$CONCOURSE_PIPELINE_RESOURCE_DIR not set"}"

export GOPATH="${PWD}/gopath"
export PATH="${GOPATH}/bin:${PATH}"

go get github.com/onsi/ginkgo/ginkgo

"${CONCOURSE_PIPELINE_RESOURCE_DIR}/bin/test" \
  -skipPackage acceptance
