#!/bin/bash

set -eux

root_dir="$PWD"

# Inputs
WL_DIR="${root_dir}/${WL_DIR:?"\$WL_DIR not set"}"

export GOPATH="${root_dir}/gopath"
export PATH="${PATH}:${GOPATH}/bin"

go get -u github.com/tools/godep
# Ensure we execute a version of ginkgo that works on this version of golang.
go get -d github.com/onsi/ginkgo/ginkgo
pushd "${GOPATH}/src/github.com/onsi/ginkgo" > /dev/null
  git checkout 07d85e6b10c4289c7d612f9b13f45ba36f66d55b
  go install github.com/onsi/ginkgo/ginkgo
popd > /dev/null

pushd "${WL_DIR}"
  godep restore

  set +e
  ./scripts/unit-tests
  result_code=$?
  NORACE=true ./scripts/integration-tests
  result_code=$(( result_code+=$? ))
  set -e
popd

exit $result_code
