---
resource_types:
- name: concourse-pipeline
  type: docker-image
  source:
    repository: robdimsdale/concourse-pipeline-resource
    tag: release-candidate

resources:
- name: robdimsdale-pipelines
  type: concourse-pipeline
  source:
    target: ((concourse-pipeline-resource-acceptance-ci/Notes/pipelines-target))
    teams:
    - name: concourse-pipeline-resource-test
      username: ((concourse-pipeline-resource-acceptance-ci/Notes/pipelines-username))
      password: ((concourse-pipeline-resource-acceptance-ci/Notes/pipelines-password))

jobs:
- name: get-robdimsdale-pipelines
  public: true
  plan:
  - get: robdimsdale-pipelines
  - task: list-all-files
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu, tag: "14.04"}
      inputs:
      - name: robdimsdale-pipelines
      run:
        path: /bin/bash
        args:
        - -c
        - |
          set -eux
          ls -alh *
- name: set-concourse-pipeline-resource-acceptance
  public: true
  plan:
  - get: robdimsdale-pipelines
  - task: print-some-value
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu, tag: "14.04"}
      run:
        path: /bin/bash
        args:
        - -c
        - |
          set -eux
          echo "some value: 123456789"
  - task: modify-config
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu, tag: "14.04"}
      inputs:
      - name: robdimsdale-pipelines
      outputs:
      - name: pipelines-out
      run:
        path: /bin/bash
        args:
        - -c
        - |
          set -eux
          sed -i'' "s/123456789/$(date +%s)/g" robdimsdale-pipelines/concourse-pipeline-resource-test-concourse-pipeline-resource-acceptance.yml
          cp robdimsdale-pipelines/* pipelines-out/
  - put: robdimsdale-pipelines
    params:
      pipelines:
      - name: concourse-pipeline-resource-acceptance
        team: concourse-pipeline-resource-test
        config_file: pipelines-out/concourse-pipeline-resource-test-concourse-pipeline-resource-acceptance.yml
