#!/bin/bash

set -eux

root_dir="$PWD"

# Inputs
WL_DIR="${root_dir}/${WL_DIR:?"\$WL_DIR not set"}"

# Outputs
RELEASE_CANDIDATE_DIR="${root_dir}/${RELEASE_CANDIDATE_DIR:?"\$RELEASE_CANDIDATE_DIR not set"}"

VERSION="$(cat version/number)"
TARGET_GOOS=${TARGET_GOOS:?}
TARGET_GOARCH=${TARGET_GOARCH:?}

export GOPATH="${root_dir}/gopath"
export PATH="${PATH}:${GOPATH}/bin"

pushd "${WL_DIR}"
  go get -u github.com/tools/godep

  godep restore

  IFS='-' read -ra arrVERSION <<< "${VERSION}"
  stripped_version="${arrVERSION[0]}"

  GOOS="${TARGET_GOOS}" \
  GOARCH="${TARGET_GOARCH}" \
  CGO_ENABLED=0 \
  go build \
    -o "${RELEASE_CANDIDATE_DIR}/wl-${TARGET_GOOS}-${TARGET_GOARCH}-${VERSION}" \
    -ldflags "-X main.version=${stripped_version}" \
    ./cmd/wl/main.go
popd
