---
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource

resources:
- name: robdimsdale-ci
  type: git
  source:
    branch: master
    uri: https://github.com/robdimsdale/robdimsdale-ci.git

- name: wl
  type: git
  source:
    uri: git@github.com:robdimsdale/wl
    branch: develop
    private_key: {{private-key}}

- name: wl-master
  type: git
  source:
    uri: git@github.com:robdimsdale/wl
    branch: master
    private_key: {{private-key}}

- name: homebrew-tap
  type: git
  source:
    uri: git@github.com:robdimsdale/homebrew-tap
    branch: master
    private_key: {{homebrew-tap-private-key}}

- name: slack-alert
  type: slack-notification
  source:
    url: {{slack-url}}

- name: tracker
  type: tracker
  source:
    token: {{tracker-token}}
    project_id: {{tracker-project-id}}
    tracker_url: https://www.pivotaltracker.com

- name: time-trigger
  type: time
  source: {interval: 12h}

- name: version
  type: semver
  source:
    bucket: wl-releases
    key: current-version
    access_key_id: {{pipeline-bucket-access-key}}
    secret_access_key: {{pipeline-bucket-secret-key}}

- name: wl-release-linux-amd64
  type: s3
  source:
    bucket: wl-releases
    regexp: wl-linux-amd64-(.*)
    access_key_id: {{pipeline-bucket-access-key}}
    secret_access_key: {{pipeline-bucket-secret-key}}

- name: wl-release-darwin-amd64
  type: s3
  source:
    bucket: wl-releases
    regexp: wl-darwin-amd64-(.*)
    access_key_id: {{pipeline-bucket-access-key}}
    secret_access_key: {{pipeline-bucket-secret-key}}

- name: wl-release-windows-amd64
  type: s3
  source:
    bucket: wl-releases
    regexp: wl-windows-amd64-(.*)
    access_key_id: {{pipeline-bucket-access-key}}
    secret_access_key: {{pipeline-bucket-secret-key}}

- name: github-release
  type: github-release
  source:
    access_token: {{github-release-access-token}}
    repository: wl
    user: robdimsdale

jobs:
- name: test
  public: true
  plan:
  - do:
    - aggregate:
      - get: robdimsdale-ci
      - get: wl
        trigger: true
      - get: time-trigger
        trigger: true
    - aggregate:
      - task: unit-tests
        file: robdimsdale-ci/wl/unit/task.yml
      - task: unit-integration-tests
        file: robdimsdale-ci/wl/integration/task.yml
        params:
          WL_ACCESS_TOKEN: {{wl-access-token}}
          WL_CLIENT_ID: {{wl-client-id}}
    on_failure:
      put: slack-alert
      params:
        silent: true
        username: concourse
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        channel: {{slack-channel}}
        text: {{slack-failure-text}}

- name: rc
  serial_groups: [version]
  public: true
  plan:
  - do:
    - aggregate:
      - get: robdimsdale-ci
      - get: wl
        passed: [test]
        trigger: true
      - get: version
        params: {pre: rc}
    - aggregate:
      - task: create-wl-release-candidate-linux-amd64
        file: robdimsdale-ci/wl/create-wl-release-candidate-linux-amd64.yml
      - task: create-wl-release-candidate-darwin-amd64
        file: robdimsdale-ci/wl/create-wl-release-candidate-darwin-amd64.yml
      - task: create-wl-release-candidate-windows-amd64
        file: robdimsdale-ci/wl/create-wl-release-candidate-windows-amd64.yml
    - aggregate:
      - put: version
        params: {file: version/number}
      - put: tracker
        params:
          repos: [wl]
      - put: wl-release-linux-amd64
        params: {file: wl-rc-linux-amd64/wl-linux-*}
      - put: wl-release-darwin-amd64
        params: {file: wl-rc-darwin-amd64/wl-darwin-*}
      - put: wl-release-windows-amd64
        params: {file: wl-rc-windows-amd64/wl-windows-*}
    on_failure:
      put: slack-alert
      params:
        silent: true
        username: concourse
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        channel: {{slack-channel}}
        text: {{slack-failure-text}}
    on_success:
      put: slack-alert
      params:
        silent: true
        username: concourse
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        channel: {{slack-channel}}
        text: {{rc-slack-success-text}}

- name: shipit
  serial_groups: [version]
  public: true
  plan:
  - aggregate:
    - get: robdimsdale-ci
    - get: wl
      passed: [rc]
    - get: version
      passed: [rc]
      params: {bump: final}
    - get: wl-release-linux-amd64
      passed: [rc]
    - get: wl-release-darwin-amd64
      passed: [rc]
    - get: wl-release-windows-amd64
      passed: [rc]
  - aggregate:
    - task: finalize-wl-release-linux-amd64
      file: robdimsdale-ci/wl/finalize-wl-release-linux-amd64.yml
    - task: finalize-wl-release-darwin-amd64
      file: robdimsdale-ci/wl/finalize-wl-release-darwin-amd64.yml
    - task: finalize-wl-release-windows-amd64
      file: robdimsdale-ci/wl/finalize-wl-release-windows-amd64.yml
  - aggregate:
    - put: version
      params: {file: version/number}
    - put: wl-master
      params:
        repository: wl
        tag: version/number
        tag_prefix: v
    - put: wl-release-linux-amd64
      params: {file: wl-final-linux-amd64/wl-linux-*}
    - put: wl-release-darwin-amd64
      params: {file: wl-final-darwin-amd64/wl-darwin-*}
    - put: wl-release-windows-amd64
      params: {file: wl-final-windows-amd64/wl-windows-*}

- name: github-release
  public: true
  plan:
  - aggregate:
    - get: robdimsdale-ci
    - get: wl
      passed: [shipit]
      trigger: true
    - get: wl-master
      passed: [shipit]
      trigger: true
    - get: wl-release-linux-amd64
      passed: [shipit]
      trigger: true
    - get: wl-release-darwin-amd64
      passed: [shipit]
      trigger: true
    - get: wl-release-windows-amd64
      passed: [shipit]
      trigger: true
  - task: most-recent-tag
    file: robdimsdale-ci/wl/most-recent-tag.yml
  - put: github-release
    params:
      name: tag/tagname
      tag: tag/tagname
      globs:
      - wl-release-linux-amd64/wl-*
      - wl-release-darwin-amd64/wl-*
      - wl-release-windows-amd64/wl-*

- name: homebrew
  public: true
  plan:
  - aggregate:
    - get: robdimsdale-ci
    - get: wl
      passed: [github-release]
      trigger: true
    - get: homebrew-tap
    - get: github-release
      passed: [github-release]
      trigger: true
  - task: create-homebrew-formula
    file: robdimsdale-ci/wl/create-homebrew-formula.yml
  - put: homebrew-tap
    params:
      repository: homebrew-tap-updated

- name: major
  public: true
  serial_groups: [version]
  plan:
  - get: version
    params: {bump: major}
  - put: version
    params: {file: version/number}

- name: minor
  public: true
  serial_groups: [version]
  plan:
  - get: version
    params: {bump: minor}
  - put: version
    params: {file: version/number}

- name: patch
  public: true
  serial_groups: [version]
  plan:
  - get: version
    passed: [shipit]
    params: {bump: patch}
    trigger: true
  - put: version
    params: {file: version/number}

groups:
- name: wl
  jobs:
  - test
  - rc
  - shipit
  - github-release
  - homebrew
  - major
  - minor
  - patch
