#!/bin/bash

set -eu

root_dir="$PWD"

# Inputs
: "${GITHUB_RELEASE_DIR:?}"
: "${HOMEBREW_TAP_DIR:?}"

# Outputs
: "${OUTPUT_DIR:?}"

GITHUB_RELEASE_DIR="${root_dir}/${GITHUB_RELEASE_DIR}"
HOMEBREW_TAP_DIR="${root_dir}/${HOMEBREW_TAP_DIR}"

OUTPUT_DIR="${root_dir}/${OUTPUT_DIR:?}"

version="$(cat "${root_dir}/github-release/version")"
wl_binary="${GITHUB_RELEASE_DIR}/wl-darwin-amd64-${version}"
output_file=${OUTPUT_DIR}/wl.rb

git clone \
  "file:///${HOMEBREW_TAP_DIR}" \
  "${OUTPUT_DIR}"

sha256=$( shasum -a 256 "${wl_binary}" | awk '{ print $1}' )

cat << EOF > "${output_file}"
require 'formula'

class Wl < Formula
  desc "golang wunderlist client"
  homepage "https://github.com/robdimsdale/wl"
  version "${version}"
  url "https://github.com/robdimsdale/wl/releases/download/v#{version}/wl-darwin-amd64-#{version}"
  sha256 "${sha256}"

  depends_on :arch => :x86_64

  def install
    mv "wl-darwin-amd64-#{version}", "wl"
    bin.install "wl"
  end

  test do
    system "#{bin}/wl"
  end
end
EOF

echo "wrote formula successfully"

echo "creating commit in ${OUTPUT_DIR}"
pushd "${OUTPUT_DIR}" > /dev/null
  git config user.name "Concourse CI"
  git config user.email "ci@robdimsdale.com"
  git add -v -A .
  git commit -v -m"Update wl to version ${version}"
popd > /dev/null
