#!/bin/sh

set -eux

root_dir="${PWD}"

# Inputs
VERSION_DIR="${root_dir}/${VERSION_DIR:?"\$VERSION_DIR not set"}"
CHECK_BINARY_DIR="${root_dir}/${CHECK_BINARY_DIR:?"\$CHECK_BINARY_DIR not set"}"
IN_BINARY_DIR="${root_dir}/${IN_BINARY_DIR:?"\$IN_BINARY_DIR not set"}"
OUT_BINARY_DIR="${root_dir}/${OUT_BINARY_DIR:?"\$OUT_BINARY_DIR not set"}"
FLY_BINARY_DIR="${root_dir}/${FLY_BINARY_DIR:?"\$FLY_BINARY_DIR not set"}"

# Outputs
FINALIZED_FILES_DIR="${root_dir}/${FINALIZED_FILES_DIR:?"\$FINALIZED_FILES_DIR not set"}"

version="$(cat "${VERSION_DIR}/number")"
if [ -z "${version}" ]; then
  echo "missing version number"
  exit 1
fi

mv \
  "${CHECK_BINARY_DIR}/check-"* \
  "${FINALIZED_FILES_DIR}/check-${version}"

mv \
  "${IN_BINARY_DIR}/in-"* \
  "${FINALIZED_FILES_DIR}/in-${version}"

mv \
  "${OUT_BINARY_DIR}/out-"* \
  "${FINALIZED_FILES_DIR}/out-${version}"

# Do not version the fly binary but ensure we provide it with the others.
mv \
  "${FLY_BINARY_DIR}/fly" \
  "${FINALIZED_FILES_DIR}/fly-bin"
