---
jobs:
- name: update-slack-name
  public: true
  plan:
  - task: update-slack-name
    config:
      platform: linux
      params:
        SLACK_URL: {{slack-url}}
      image_resource:
        type: docker-image
        source: {repository: robdimsdale/middleman-site-docker-image}
      run:
        path: /bin/bash
        args:
        - -c
        - |
          set -eu
          curl \
          -s \
          "${SLACK_URL}"
