---
resources:
- name: robdimsdale-ci
  type: git
  source:
    uri: https://github.com/robdimsdale/robdimsdale-ci
    branch: master

- name: reports-develop
  type: git
  source:
    uri: git@github.com:robdimsdale/reports
    branch: develop
    private_key: ((reports-ci/Notes/reports-private-key))

- name: reports-master
  type: git
  source:
    uri: git@github.com:robdimsdale/reports
    branch: master
    private_key: ((reports-ci/Notes/reports-private-key))

- name: reports-cf-app-staging
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: ((reports-ci/Notes/cf-user))
    password: ((reports-ci/Notes/cf-password))
    organization: ((reports-ci/Notes/cf-org-staging))
    space: ((reports-ci/Notes/cf-space-staging))
    skip_cert_check: false

- name: reports-cf-app-production
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: ((reports-ci/Notes/cf-user))
    password: ((reports-ci/Notes/cf-password))
    organization: ((reports-ci/Notes/cf-org-production))
    space: ((reports-ci/Notes/cf-space-production))
    skip_cert_check: false

- name: daily
  type: time
  source:
    interval: 24h

jobs:
- name: build-deploy-site-develop
  public: true
  serial: true
  plan:
  - aggregate:
    - get: robdimsdale-ci
    - get: daily
      trigger: true
    - get: reports-develop
      trigger: true
  - put: reports-cf-app-staging
    params:
      manifest: reports-develop/manifest.yml
      path: reports-develop

- name: build-deploy-site-master
  public: true
  serial: true
  plan:
  - aggregate:
    - get: robdimsdale-ci
    - get: daily
      trigger: true
    - get: reports-master
      trigger: true
  - put: reports-cf-app-production
    params:
      manifest: reports-master/manifest.yml
      path: reports-master
