---
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource

resources:
- name: robdimsdale-ci
  type: git
  source:
    uri: https://github.com/robdimsdale/robdimsdale-ci
    branch: master

- name: website-develop
  type: git
  source:
    uri: git@github.com:hallez/hrz-website
    branch: develop
    private_key: ((hrz-website-ci-private-key/Notes))

- name: website-master
  type: git
  source:
    uri: git@github.com:hallez/hrz-website
    branch: master
    private_key: ((hrz-website-ci-private-key/Notes))

- name: slack_alert
  type: slack-notification
  source:
    url: ((hrz-website-ci/Notes/slack-url))

- name: tracker
  type: tracker
  source:
    token: ((hrz-website-ci/Notes/tracker-token))
    project_id: ((hrz-website-ci/Notes/tracker-project-id))
    tracker_url: https://www.pivotaltracker.com

- name: website-app-staging
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: ((hrz-website-ci/Notes/cf-user))
    password: ((hrz-website-ci/Notes/cf-password))
    organization: ((hrz-website-ci/Notes/cf-org-develop))
    space: ((hrz-website-ci/Notes/cf-space-develop))

jobs:
- name: build-deploy-site-develop
  public: true
  serial: true
  plan:
  - aggregate:
    - get: robdimsdale-ci
    - get: website
      resource: website-develop
      trigger: true
  - do:
    - task: build-site
      file: robdimsdale-ci/hrz-website/build_site/task.yml
    - task: add-staticfile-auth
      file: robdimsdale-ci/hrz-website/add_staticfile_auth/task.yml
      input_mapping:
        website: website-built
      params:
        STATIC_FILE_AUTH: ((hrz-website-ci/Notes/static-file-auth-develop))
    - task: create-cf-manifest
      file: robdimsdale-ci/hrz-website/create_cf_manifest/task.yml
      input_mapping:
        website: website-with-staticfile-auth
      output_mapping:
        website-with-cf-manifest: final-website
      params:
        APPLICATION_NAME: ((hrz-website-ci/Notes/cf-application-develop))
        ADDITIONAL_ROUTE: ((hrz-website-ci/Notes/additional-route-develop))
    - put: website-app-staging
      params:
        manifest: final-website/manifest.yml
        current_app_name: ((hrz-website-ci/Notes/cf-application-develop))
        path: final-website
        environment_variables:
          FORCE_HTTPS: "true"
    on_success:
      aggregate:
      - put: slack_alert
        params:
          silent: true
          username: concourse
          icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
          channel: ((hrz-website-ci/Notes/slack-channel))
          text: ((hrz-website-ci/Notes/slack-develop-success-text))
      - put: tracker
        params: {repos: [website]}
    on_failure:
      put: slack_alert
      params:
        silent: true
        username: concourse
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        channel: ((hrz-website-ci/Notes/slack-channel))
        text: ((hrz-website-ci/Notes/slack-develop-failure-text))

- name: build-deploy-site-master
  public: true
  serial: true
  plan:
  - aggregate:
    - get: robdimsdale-ci
    - get: website
      resource: website-master
      trigger: true
  - do:
    - task: build-site
      file: robdimsdale-ci/hrz-website/build_site/task.yml
    - task: deploy-site
      file: robdimsdale-ci/dimsdale-website/deploy_site/task.yml
      input_mapping:
        website: website-built
      params:
        CF_USER: ((hrz-website-ci/Notes/cf-user))
        CF_PASSWORD: ((hrz-website-ci/Notes/cf-password))
        CF_ORG: ((hrz-website-ci/Notes/cf-org-master))
        CF_SPACE: ((hrz-website-ci/Notes/cf-space-master))
        CF_APPLICATION: ((hrz-website-ci/Notes/cf-application-master))
        STATIC_FILE_AUTH: ((hrz-website-ci/Notes/static-file-auth-master))
    on_success:
      put: slack_alert
      params:
        silent: true
        username: concourse
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        channel: ((hrz-website-ci/Notes/slack-channel))
        text: ((hrz-website-ci/Notes/slack-master-success-text))
    on_failure:
      put: slack_alert
      params:
        silent: true
        username: concourse
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        channel: ((hrz-website-ci/Notes/slack-channel))
        text: ((hrz-website-ci/Notes/slack-master-failure-text))
