---
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource

resources:
- name: robdimsdale-ci
  type: git
  source:
    uri: https://github.com/robdimsdale/robdimsdale-ci
    branch: master

- name: website-repo
  type: git
  source:
    uri: git@github.com:hallez/hrz-website
    branch: master
    private_key: ((hrz-website-ci-private-key/Notes))

- name: slack_alert
  type: slack-notification
  source:
    url: ((hrz-website-ci/Notes/slack-url))

- name: tracker
  type: tracker
  source:
    token: ((hrz-website-ci/Notes/tracker-token))
    project_id: ((hrz-website-ci/Notes/tracker-project-id))
    tracker_url: https://www.pivotaltracker.com

- name: website-app-staging
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: ((hrz-website-ci/Notes/cf-user))
    password: ((hrz-website-ci/Notes/cf-password))
    organization: ((hrz-website-ci/Notes/cf-org-staging))
    space: ((hrz-website-ci/Notes/cf-space-staging))

- name: website-app-master
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: ((hrz-website-ci/Notes/cf-user))
    password: ((hrz-website-ci/Notes/cf-password))
    organization: ((hrz-website-ci/Notes/cf-org-master))
    space: ((hrz-website-ci/Notes/cf-space-master))

- name: daily
  type: time
  source:
    interval: 24h

jobs:
- name: staging
  public: true
  serial: true
  plan:
  - aggregate:
    - get: robdimsdale-ci
    - get: daily
      trigger: true
    - get: website
      resource: website-repo
      trigger: true
  - do:
    - task: build-site
      file: robdimsdale-ci/staticfile-website/build-hugo-site/task.yml
      params:
        BASE_URL: ((hrz-website-ci/Notes/base-url-staging))
    - task: add-staticfile-auth
      file: robdimsdale-ci/staticfile-website/add_staticfile_auth/task.yml
      input_mapping:
        website: website-built
      params:
        STATIC_FILE_AUTH: ((hrz-website-ci/Notes/static-file-auth-staging))
    - task: create-cf-manifest
      file: robdimsdale-ci/staticfile-website/create_cf_manifest/task.yml
      input_mapping:
        website: website-with-staticfile-auth
      output_mapping:
        website-with-cf-manifest: final-website
      params:
        APPLICATION_NAME: ((hrz-website-ci/Notes/cf-application-staging))
        ADDITIONAL_ROUTE: ((hrz-website-ci/Notes/additional-route-staging))
    - put: website-app-staging
      params:
        manifest: final-website/manifest.yml
        current_app_name: ((hrz-website-ci/Notes/cf-application-staging))
        path: final-website
        environment_variables:
          FORCE_HTTPS: "true"
    on_success:
      aggregate:
      - put: slack_alert
        params:
          silent: true
          username: concourse
          icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
          channel: ((hrz-website-ci/Notes/slack-channel))
          text: ((hrz-website-ci/Notes/slack-staging-success-text))
      - put: tracker
        params: {repos: [website]}
    on_failure:
      put: slack_alert
      params:
        silent: true
        username: concourse
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        channel: ((hrz-website-ci/Notes/slack-channel))
        text: ((hrz-website-ci/Notes/slack-staging-failure-text))

- name: production
  public: true
  serial: true
  plan:
  - aggregate:
    - get: robdimsdale-ci
    - get: website
      resource: website-repo
      passed: [staging]
  - do:
    - task: build-site
      file: robdimsdale-ci/staticfile-website/build-hugo-site/task.yml
    - task: create-cf-manifest
      file: robdimsdale-ci/staticfile-website/create_cf_manifest/task.yml
      input_mapping:
        website: website-built
      output_mapping:
        website-with-cf-manifest: final-website
      params:
        APPLICATION_NAME: ((hrz-website-ci/Notes/cf-application-master))
        ADDITIONAL_ROUTE: ((hrz-website-ci/Notes/additional-route-master))
    - put: website-app-master
      params:
        manifest: final-website/manifest.yml
        current_app_name: ((hrz-website-ci/Notes/cf-application-master))
        path: final-website
        environment_variables:
          FORCE_HTTPS: "true"
    on_success:
      put: slack_alert
      params:
        silent: true
        username: concourse
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        channel: ((hrz-website-ci/Notes/slack-channel))
        text: ((hrz-website-ci/Notes/slack-master-success-text))
    on_failure:
      put: slack_alert
      params:
        silent: true
        username: concourse
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        channel: ((hrz-website-ci/Notes/slack-channel))
        text: ((hrz-website-ci/Notes/slack-master-failure-text))
