#!/bin/sh

set -eux

root_dir="${PWD}"

# Inputs
VERSION_DIR="${root_dir}/${VERSION_DIR:?"\$VERSION_DIR not set"}"
BUILT_BINARIES_DIR="${root_dir}/${BUILT_BINARIES_DIR:?"\$BUILT_BINARIES_DIR not set"}"

# Outputs
VERSIONED_BINARIES_DIR="${root_dir}/${VERSIONED_BINARIES_DIR:?"\$VERSIONED_BINARIES_DIR not set"}"

version="$(cat "${VERSION_DIR}/version")"
if [ -z "${version}" ]; then
  echo "missing version file"
  exit 1
fi

mv \
  "${BUILT_BINARIES_DIR}/check" \
  "${VERSIONED_BINARIES_DIR}/check-${version}"

mv \
  "${BUILT_BINARIES_DIR}/in" \
  "${VERSIONED_BINARIES_DIR}/in-${version}"

mv \
  "${BUILT_BINARIES_DIR}/out" \
  "${VERSIONED_BINARIES_DIR}/out-${version}"

