#!/bin/sh

set -eux

root_dir="${PWD}"

# Inputs
VERSION_DIR="${root_dir}/${VERSION_DIR:?"\$VERSION_DIR not set"}"
CONCOURSE_PIPELINE_RESOURCE_IMAGE_DIR="${root_dir}/${CONCOURSE_PIPELINE_RESOURCE_IMAGE_DIR:?"\$CONCOURSE_PIPELINE_RESOURCE_IMAGE_DIR not set"}"

# Outputs
VERSIONED_ROOTFS_DIR="${root_dir}/${VERSIONED_ROOTFS_DIR:?"\$VERSIONED_ROOTFS_DIR not set"}"

version="$(cat "${VERSION_DIR}/number")"
if [ -z "${version}" ]; then
  echo "missing version number"
  exit 1
fi

mv \
  "${CONCOURSE_PIPELINE_RESOURCE_IMAGE_DIR}/rootfs.tar" \
  "${VERSIONED_ROOTFS_DIR}/rootfs-${version}.tar"
