#!/bin/bash

set -eu
set -o pipefail

root_dir="$PWD"

# Outputs
output_dir="${root_dir}/homebrew-tap-updated"

version="$(cat "${root_dir}/version/version")"
wl_binary="${root_dir}/github-release/wl-${version}-darwin-amd64"
output_file=${output_dir}/wl-cli.rb

git clone \
  "file:///${root_dir}/homebrew-tap" \
  "${output_dir}"

sha256=$( shasum -a 256 "${wl_binary}" | awk '{ print $1}' )

cat << EOF > "${output_file}"
require 'formula'

class WlCli < Formula
  desc "Unofficial Wunderlist CLI"
  homepage "https://github.com/robdimsdale/wl-cli"
  version "${version}"
  url "https://github.com/robdimsdale/wl-cli/releases/download/v#{version}/wl-darwin-amd64-#{version}"
  sha256 "${sha256}"

  depends_on :arch => :x86_64

  def install
    mv "wl-#{version}-darwin-amd64", "wl"
    bin.install "wl"
  end

  test do
    system "#{bin}/wl"
  end
end
EOF

echo "wrote formula successfully"

echo "creating commit in ${output_dir}"
pushd "${output_dir}" > /dev/null
  git config user.name "Concourse CI"
  git config user.email "ci@robdimsdale.com"
  git add -v -A .
  git commit -v -m"Update wl-cli to version ${version}"
popd > /dev/null
