#!/bin/bash

set -eux

root_dir="$PWD"

# Inputs
: "${RC_DIR:?}"
: "${GOOS:?}"
: "${GOARCH:?}"

# Outputs
: "${FINAL_DIR:?}"

FINAL_DIR="${root_dir}/${FINAL_DIR:?}"

version="$(cat version/number)"

mv \
  "${RC_DIR}"/wl-* \
  "${FINAL_DIR}/wl-${GOOS}-${GOARCH}-${version}"
