#!/bin/bash

set -eux

root_dir="$PWD"

# Inputs
WL_DIR="${root_dir}/${WL_DIR:?"\$WL_DIR not set"}"

export GOPATH="${root_dir}/${GOPATH}"
export PATH="${PATH}:${GOPATH}/bin"

go get -u github.com/golang/lint/golint

pushd "${WL_DIR}"
  go install ./vendor/github.com/onsi/ginkgo/ginkgo

  set +e
  ./scripts/go-vet
  result_code=$?

  ./scripts/unit-tests
  result_code=$(( result_code+=$? ))

  ./scripts/integration-tests
  result_code=$(( result_code+=$? ))

  set -e
popd

exit $result_code
