#!/bin/sh

set -eux

website_dir="${PWD}/website"
website_built_dir="${PWD}/website-built"

cp -R "${website_dir}/"* "${website_built_dir}"
cp -R "${website_dir}/.git" "${website_built_dir}"
cp -R "${website_dir}/.gitignore" "${website_built_dir}"

(
  cd "${website_built_dir}"

  if [ "${BASE_URL}" = "" ]; then
    hugo -d build
  else
    hugo -d build -b "${BASE_URL}"
  fi
)
