#!/bin/bash

set -eu

# Inputs
: "${WL_DIR:?}"
: "${GOOS:?}"
: "${GOARCH:?}"

# Outputs
: "${OUTPUT_DIR:?}"

root_dir="$PWD"

WL_DIR="${root_dir}/${WL_DIR}"
OUTPUT_DIR="${root_dir}/${OUTPUT_DIR}"

version="$(cat version/number)"

IFS='-' read -ra version_array <<< "${version}"
stripped_version="${version_array[0]}"

export GOPATH="${root_dir}/gopath"
export PATH="${PATH}:${GOPATH}/bin"

echo "CGO_ENABLED: ${CGO_ENABLED}"
echo "building: ${TARGET_GOOS}-${TARGET_GOARCH}-${version}"

go build \
  -o "${OUTPUT_DIR}/wl-${TARGET_GOOS}-${TARGET_GOARCH}-${version}" \
  -ldflags "-X main.version=${stripped_version}" \
  "${WL_DIR}/cmd/wl/main.go"
