#!/bin/bash

set -eux

root_dir="${PWD}"

# Outputs
OUTPUTS_DIR="${root_dir}/${OUTPUTS_DIR:?"\$OUTPUTS_DIR not set"}"

curl \
  -o "${OUTPUTS_DIR}/fly"\
  'https://concourse.robdimsdale.com/api/v1/cli?arch=amd64&platform=linux'

chmod +x "${OUTPUTS_DIR}/fly"
