#!/bin/bash

set -eux

root_dir="$PWD"
garagepi_dir="github.com/robdimsdale/garagepi"
scripts_dir="${garagepi_dir}/scripts/"

pushd "${root_dir}/${garagepi_dir}" > /dev/null
  go get github.com/onsi/ginkgo/ginkgo
  go get github.com/tools/godep

  godep restore
popd > /dev/null

set +e
"${scripts_dir}/unit-tests"
result_code=$(( result_code+=$? ))
"${scripts_dir}/integration-tests"
result_code=$(( result_code+=$? ))
set -e

exit $result_code
