---
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource

resources:
- name: robdimsdale-ci
  type: git
  source:
    uri: https://github.com/robdimsdale/robdimsdale-ci
    branch: master

- name: website-develop
  type: git
  source:
    uri: git@github.com:robdimsdale/dimsdale-website
    branch: develop
    private_key: ((dimsdale-website-ci-private-key/Notes))

- name: website-master
  type: git
  source:
    uri: git@github.com:robdimsdale/dimsdale-website
    branch: master
    private_key: ((dimsdale-website-ci-private-key/Notes))

- name: slack_alert
  type: slack-notification
  source:
    url: ((dimsdale-website-ci/Notes/slack-url))

- name: website-app-staging
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: ((dimsdale-website-ci/Notes/cf-user))
    password: ((dimsdale-website-ci/Notes/cf-password))
    organization: ((dimsdale-website-ci/Notes/cf-org-staging))
    space: ((dimsdale-website-ci/Notes/cf-space-staging))

- name: website-app-master
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: ((dimsdale-website-ci/Notes/cf-user))
    password: ((dimsdale-website-ci/Notes/cf-password))
    organization: ((dimsdale-website-ci/Notes/cf-org-master))
    space: ((dimsdale-website-ci/Notes/cf-space-master))

- name: daily
  type: time
  source:
    interval: 24h

jobs:
- name: build-deploy-site-staging
  public: true
  serial: true
  plan:
  - aggregate:
    - get: robdimsdale-ci
    - get: daily
      trigger: true
    - get: website
      resource: website-develop
      trigger: true
  - do:
    - task: build-site
      file: robdimsdale-ci/staticfile-website/build_site/task.yml
    - task: copy-resume
      file: robdimsdale-ci/dimsdale-website/copy_resume/task.yml
      input_mapping:
        website: website-built
    - task: add-staticfile-auth
      file: robdimsdale-ci/staticfile-website/add_staticfile_auth/task.yml
      input_mapping:
        website: website-with-resume
      params:
        STATIC_FILE_AUTH: ((dimsdale-website-ci/Notes/static-file-auth-staging))
    - task: create-cf-manifest
      file: robdimsdale-ci/staticfile-website/create_cf_manifest/task.yml
      input_mapping:
        website: website-with-staticfile-auth
      output_mapping:
        website-with-cf-manifest: final-website
      params:
        APPLICATION_NAME: ((dimsdale-website-ci/Notes/cf-application-staging))
        ADDITIONAL_ROUTE: ((dimsdale-website-ci/Notes/additional-route-staging))
    - put: website-app-staging
      params:
        manifest: final-website/manifest.yml
        current_app_name: ((dimsdale-website-ci/Notes/cf-application-staging))
        path: final-website
        environment_variables:
          FORCE_HTTPS: "true"
    on_success:
      put: slack_alert
      params:
        silent: true
        username: concourse
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        channel: ((dimsdale-website-ci/Notes/slack-channel))
        text: ((dimsdale-website-ci/Notes/slack-staging-success-text))
    on_failure:
      put: slack_alert
      params:
        silent: true
        username: concourse
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        channel: ((dimsdale-website-ci/Notes/slack-channel))
        text: ((dimsdale-website-ci/Notes/slack-staging-failure-text))

- name: build-deploy-site-master
  public: true
  serial: true
  plan:
  - aggregate:
    - get: robdimsdale-ci
    - get: daily
      trigger: true
    - get: website
      resource: website-master
      trigger: true
  - do:
    - task: build-site
      file: robdimsdale-ci/staticfile-website/build_site/task.yml
    - task: copy-resume
      file: robdimsdale-ci/dimsdale-website/copy_resume/task.yml
      input_mapping:
        website: website-built
    - task: create-cf-manifest
      file: robdimsdale-ci/staticfile-website/create_cf_manifest/task.yml
      input_mapping:
        website: website-with-resume
      output_mapping:
        website-with-cf-manifest: final-website
      params:
        APPLICATION_NAME: ((dimsdale-website-ci/Notes/cf-application-master))
        ADDITIONAL_ROUTE: ((dimsdale-website-ci/Notes/additional-route-master))
    - put: website-app-master
      params:
        manifest: final-website/manifest.yml
        current_app_name: ((dimsdale-website-ci/Notes/cf-application-master))
        path: final-website
        environment_variables:
          FORCE_HTTPS: "true"
    on_success:
      put: slack_alert
      params:
        silent: true
        username: concourse
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        channel: ((dimsdale-website-ci/Notes/slack-channel))
        text: ((dimsdale-website-ci/Notes/slack-master-success-text))
    on_failure:
      put: slack_alert
      params:
        silent: true
        username: concourse
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        channel: ((dimsdale-website-ci/Notes/slack-channel))
        text: ((dimsdale-website-ci/Notes/slack-master-failure-text))
