---
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource

resources:
- name: robdimsdale-ci
  type: git
  source:
    uri: https://github.com/robdimsdale/robdimsdale-ci
    branch: master

- name: website-develop
  type: git
  source:
    uri: git@github.com:robdimsdale/dimsdale-website
    branch: develop
    private_key: ((dimsdale-website-ci-private-key/Notes))

- name: website-master
  type: git
  source:
    uri: git@github.com:robdimsdale/dimsdale-website
    branch: master
    private_key: ((dimsdale-website-ci-private-key/Notes))

- name: slack_alert
  type: slack-notification
  source:
    url: ((dimsdale-website-ci/Notes/slack-url))

jobs:
- name: build-deploy-site-develop
  public: true
  serial: true
  plan:
  - aggregate:
    - get: robdimsdale-ci
    - get: website
      resource: website-develop
      trigger: true
  - do:
    - task: build-site
      file: robdimsdale-ci/dimsdale-website/build_site/task.yml
    - task: deploy-site
      file: robdimsdale-ci/dimsdale-website/deploy_site/task.yml
      input_mapping:
        website: website-built
      params:
        CF_USER: ((dimsdale-website-ci/Notes/cf-user))
        CF_PASSWORD: ((dimsdale-website-ci/Notes/cf-password))
        CF_ORG: ((dimsdale-website-ci/Notes/cf-org-develop))
        CF_SPACE: ((dimsdale-website-ci/Notes/cf-space-develop))
        CF_APPLICATION: ((dimsdale-website-ci/Notes/cf-application-develop))
        STATIC_FILE_AUTH: ((dimsdale-website-ci/Notes/static-file-auth-develop))
    on_success:
      put: slack_alert
      params:
        silent: true
        username: concourse
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        channel: ((dimsdale-website-ci/Notes/slack-channel))
        text: ((dimsdale-website-ci/Notes/slack-develop-success-text))
    on_failure:
      put: slack_alert
      params:
        silent: true
        username: concourse
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        channel: ((dimsdale-website-ci/Notes/slack-channel))
        text: ((dimsdale-website-ci/Notes/slack-develop-failure-text))

- name: build-deploy-site-master
  public: true
  serial: true
  plan:
  - aggregate:
    - get: robdimsdale-ci
    - get: website
      resource: website-master
      trigger: true
  - do:
    - task: build-site
      file: robdimsdale-ci/dimsdale-website/build_site/task.yml
    - task: deploy-site
      file: robdimsdale-ci/dimsdale-website/deploy_site/task.yml
      input_mapping:
        website: website-built
      params:
        CF_USER: ((dimsdale-website-ci/Notes/cf-user))
        CF_PASSWORD: ((dimsdale-website-ci/Notes/cf-password))
        CF_ORG: ((dimsdale-website-ci/Notes/cf-org-master))
        CF_SPACE: ((dimsdale-website-ci/Notes/cf-space-master))
        CF_APPLICATION: ((dimsdale-website-ci/Notes/cf-application-master))
        STATIC_FILE_AUTH: ((dimsdale-website-ci/Notes/static-file-auth-master))
    on_success:
      put: slack_alert
      params:
        silent: true
        username: concourse
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        channel: ((dimsdale-website-ci/Notes/slack-channel))
        text: ((dimsdale-website-ci/Notes/slack-master-success-text))
    on_failure:
      put: slack_alert
      params:
        silent: true
        username: concourse
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        channel: ((dimsdale-website-ci/Notes/slack-channel))
        text: ((dimsdale-website-ci/Notes/slack-master-failure-text))
