#!/bin/bash

set -eux

website_dir="${PWD}/website"
website_built_dir="${PWD}/website-built"

cp -R "${website_dir}" "${website_built_dir}"

pushd "${website_built_dir}" > /dev/null
  bundle
  bundle exec middleman build --clean

  cp \
    "source/resume/robdimsdale-resume.html" \
    "build/resume/robdimsdale-resume.html"
popd > /dev/null
