#!/bin/bash

set -eux

website_dir="${PWD}/website"
website_built_dir="${PWD}/website-with-resume"

shopt -s dotglob
cp -R "${website_dir}/"* "${website_built_dir}"
shopt -u dotglob

cp \
  "${website_built_dir}/source/resume/robdimsdale-resume.html" \
  "${website_built_dir}/build/resume/robdimsdale-resume.html"
