#!/bin/bash

set -eu

root_dir="$PWD"

# Inputs
: "${GOOS:?}"
: "${GOARCH:?}"

version="$(cat version/version)"

mv \
  "${root_dir}/wl-rc"/wl-* \
  "${root_dir}/wl-final/wl-${version}-${GOOS}-${GOARCH}"
